version: "3.9"

services:
  frontend:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - type: bind
        source: /git-repos/material-applications/example-frontend
        target: /app
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://192.168.232.115:8080
    command: sh -c "npm install --production && npm run build && npm install -g serve && serve -s -l 5000 build"
    #container_name: frontend_app1

  backend:
    image: golang:1.16
    working_dir: /app
    volumes:
      - type: bind
        source: /git-repos/material-applications/example-backend
        target: /app

    ports:
      - 8080:8080
    #depends_on:
      #- redis
      #- db
    environment:
      - REQUEST_ORIGIN=http://192.168.232.115:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    command: sh -c "go build -o server && ./server"
   #container_name: backend_app

  redis:
   image: redis:latest
   ports:
     - 6379:6379

  postgres:
   image: postgres:13.2-alpine
   restart: unless-stopped
   ports:
     - 5432:5432
   volumes:
     - ./database:/var/lib/postgresql/data
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DATABASE=postgres
   
